version: '3.8'

services:
    # Tempo Container
    tempo_svc:
        image: grafana/tempo:2.4.1
        command: [ "-config.file=/etc/tempo.yaml" ]
        volumes:
            - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
            - tempo_data:/tmp/tempo
        ports:
            - 14268:14268    # jaeger ingest
            - 3200:3200      # tempo
            - 9095:9095      # tempo grpc
            - 4317:4317      # otlp grpc
            - 4318:4318      # otlp http
            - 9411:9411      # zipkin

    # Prometheus Container
    prometheus_svc:
        image: prom/prometheus:v2.51.2
        command:
          - --config.file=/etc/prometheus/prometheus.yml
          - --web.enable-remote-write-receiver
          - --enable-feature=exemplar-storage
          - --storage.tsdb.path=/prometheus
        volumes:
            - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        ports:
            - 9090:9090
        restart: unless-stopped

    # Grafana Container
    grafana_svc:
        image: grafana/grafana:10.4.2
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
        volumes:
          - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
          - grafana_data:/var/lib/grafana
          - grafana_logs:/var/log/grafana
        ports:
            - 3000:3000
        restart: unless-stopped

    # Loki Container
    loki_svc:
        image: grafana/loki:3.0.0
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - 3100:3100
        restart: unless-stopped

    # Promtail Container
    # promtail_svc:
    #     image: grafana/promtail:2.9.7
    #     command: -config.file=/etc/promtail/config.yml
    #     volumes:
    #         - ./var/logs/:/var/log
    #     restart: unless-stopped

    # Pyroscope Container
    pyroscope_svc:
        image: grafana/pyroscope:1.5.0
        ports:
            - 4040:4040
        restart: unless-stopped

    # Alertmanager Container
    alertmanager_svc:
        image: prom/alertmanager:v0.27.0
        command: --config.file=/config/alertmanager/alertmanager.yml --log.level=debug
        ports:
          - 9093:9093
        volumes:
          - ./configs/alertmanager/alertmanager.yml:/config/alertmanager.yml"
          - alertmanager_data:/data
        restart: unless-stopped

volumes:
  prometheus_data:
    driver: local

  grafana_data:
    driver: local

  grafana_logs:
    driver: local

  tempo_data:
    driver: local

  alertmanager_data:
    driver: local
