version: '3'

services:
    # Prometheus Container
    prometheus_svc:
        image: prom/prometheus:v2.49.1
        command: --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        ports:
            - 9090:9090
        restart: unless-stopped
        networks:
          - overlay

    # Grafana Container
    grafana_svc:
        image: grafana/grafana:10.3.1
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - 3000:3000
        volumes:
          - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
          - grafana_data:/var/lib/grafana
          - grafana_logs:/var/log/grafana
        depends_on:
            - prometheus_svc
        restart: unless-stopped
        networks:
          - overlay

networks:
  overlay:
    driver: bridge

volumes:
  prometheus_data:
    driver: local

  grafana_data:
    driver: local

  grafana_logs:
    driver: local
