# my global config
global:
  evaluation_interval: 15s
  external_labels:
    monitor: cougar-monitor
  scrape_interval: 15s
rule_files: ~
scrape_configs:
  -
    job_name: prometheus
    scrape_interval: 5s
    static_configs:
      -
        targets:
          - "localhost:9090"
