# my global config
global:
  scrape_interval:     15s
  external_labels:
    monitor: cougar-monitor
  evaluation_interval: 15s

rule_files: ~
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo_svc:3200' ]

# Change to different values
remote_write:
  basic_auth:
    username: admin
    password: password
